### ISSUE TITLE
Inconsistencies between URANUS and DISCOVER

### ISSUE THREAD

**Issue by aninramesh** [ReedEspinosa/GSFC-GRASP-Python-Interface#5]
The retrieval code is not working in DISCOVER when "relative_polarization_components" for measurements is used in FWD simulations. However, this works fine in URANUS. An easy hack was to use the "absolute_polarization_components" in the FWD simulations. This issue needs to be explored more .....

**Comment by aninramesh** [comment]
Error message was this..

```
1 pixels processed in    11.17 seconds ( 0.09 pixels/second)
Forward model "truth" obtained
Inverting noised-up measurements...
Traceback (most recent call last):
  File "/gpfsm/dnb32/aputhukk/git/GSFC-Retrieval-Simulators/Examples/runRetrievalSimulation.py", line 63, in <module>
    simA.runSim(cstmFwdYAML, bckYAMLpath, Nsims, maxCPU=maxCPU, savePath=savePath, \
  File "/gpfsm/dnb32/aputhukk/git/GSFC-Retrieval-Simulators/simulateRetrieval.py", line 101, in runSim
    nowPix.populateFromRslt(self.rsltFwd[i], radianceNoiseFun=radianceNoiseFun, verbose=localVerbose)
  File "/gpfsm/dnb32/aputhukk/git/GSFC-GRASP-Python-Interface/runGRASP.py", line 1110, in populateFromRslt
    msDct = self.formatMeas(msDct) # this will tile the above msTyp times
  File "/gpfsm/dnb32/aputhukk/git/GSFC-GRASP-Python-Interface/runGRASP.py", line 1139, in formatMeas
    assert newMeas['thetav'].shape[0]==newMeas['phi'].shape[0] and \
AssertionError: Each measurement must conform to the following format:
            For more than one measurement type or viewing geometry pass msTyp, nbvm, thtv, phi and msrments as vectors: 
            len(msrments)=len(thtv)=len(phi)=sum(nbvm); len(msTyp)=len(nbvm) 
            msrments=[meas[msTyp[0],thtv[0],phi[0]], meas[msTyp[0],thtv[1],phi[1]],...,meas[msTyp[0],thtv[nbvm[0]],phi[nbvm[0]]],meas[msTyp[1],thtv[nbvm[0]+1],phi[nbvm[0]+1]],...]
```
